from app.database import SessionLocal, Base, engine
from app.models.event import WeatherEvent

Base.metadata.create_all(bind=engine)

db = SessionLocal()

events = [
    {
        "id": "evt-1001",
        "type": "Flood",
        "title": "Severe urban flooding in low-lying areas",
        "state": "Kerala",
        "city": "Kochi",
        "lat": 9.9312,
        "lng": 76.2673,
        "datetime": "2026-08-28T06:20:00+05:30",
        "description": "Continuous heavy downpour over 36 hours has inundated several wards. Water levels rising near the backwaters; multiple relief camps opened.",
        "source": "Government",
        "source_name": "Kerala State Disaster Management Authority",
        "trust_score": 96,
        "status": "verified",
        "media_url": "/media/flood.png",
        "ml_classification": "Flood — Urban Inundation",
        "ml_confidence": 0.97,
        "affected_population": 48000,
    },
    {
        "id": "evt-1002",
        "type": "Cyclone",
        "title": "Cyclonic storm approaching eastern coast",
        "state": "Odisha",
        "city": "Puri",
        "lat": 19.8135,
        "lng": 85.8312,
        "datetime": "2026-08-28T04:10:00+05:30",
        "description": "A deep depression has intensified into a cyclonic storm over the Bay of Bengal. Landfall expected within 18 hours with wind speeds up to 120 km/h.",
        "source": "Government",
        "source_name": "India Meteorological Department",
        "trust_score": 98,
        "status": "high-risk",
        "media_url": "/media/cyclone.png",
        "ml_classification": "Cyclone — Severe",
        "ml_confidence": 0.99,
        "affected_population": 210000,
    },
    {
        "id": "evt-1003",
        "type": "Heavy Rain",
        "title": "Intense rainfall triggers waterlogging",
        "state": "Maharashtra",
        "city": "Mumbai",
        "lat": 19.076,
        "lng": 72.8777,
        "datetime": "2026-08-28T07:45:00+05:30",
        "description": "Red alert issued as the city records 210mm rain in 12 hours. Local train services disrupted on the Western line.",
        "source": "News Website",
        "source_name": "National Weather Wire",
        "trust_score": 82,
        "status": "verified",
        "media_url": "/media/heavy-rain.png",
        "ml_classification": "Heavy Rainfall — Extreme",
        "ml_confidence": 0.91,
        "affected_population": 95000,
    },
    {
        "id": "evt-1004",
        "type": "Landslide",
        "title": "Landslide blocks national highway",
        "state": "Himachal Pradesh",
        "city": "Manali",
        "lat": 32.2396,
        "lng": 77.1887,
        "datetime": "2026-08-27T22:30:00+05:30",
        "description": "A hillside slope collapsed onto NH-3 following prolonged rain. Traffic diverted; rescue teams clearing debris.",
        "source": "Citizen Report",
        "source_name": "Verified citizen — R. Thakur",
        "trust_score": 64,
        "status": "pending",
        "media_url": "/media/landslide.png",
        "ml_classification": "Landslide — Debris Flow",
        "ml_confidence": 0.78,
        "affected_population": 3200,
    },
    {
        "id": "evt-1005",
        "type": "Heatwave",
        "title": "Prolonged heatwave conditions persist",
        "state": "Rajasthan",
        "city": "Jaisalmer",
        "lat": 26.9157,
        "lng": 70.9083,
        "datetime": "2026-08-27T15:00:00+05:30",
        "description": "Temperatures crossed 47°C for the third consecutive day. Health advisory issued for outdoor workers.",
        "source": "Government",
        "source_name": "India Meteorological Department",
        "trust_score": 93,
        "status": "verified",
        "media_url": "/media/heatwave.png",
        "ml_classification": "Heatwave — Severe",
        "ml_confidence": 0.94,
        "affected_population": 27000,
    },
    {
        "id": "evt-1006",
        "type": "Storm",
        "title": "Thunderstorm with lightning reported",
        "state": "West Bengal",
        "city": "Kolkata",
        "lat": 22.5726,
        "lng": 88.3639,
        "datetime": "2026-08-28T05:30:00+05:30",
        "description": "Squally thunderstorm with frequent lightning. Several trees uprooted in the southern suburbs.",
        "source": "Social Media",
        "source_name": "Aggregated social signals",
        "trust_score": 58,
        "status": "pending",
        "media_url": "/media/storm.png",
        "ml_classification": "Thunderstorm — Moderate",
        "ml_confidence": 0.72,
        "affected_population": 12000,
    },
    {
        "id": "evt-1007",
        "type": "Flood",
        "title": "River breaches embankment",
        "state": "Assam",
        "city": "Guwahati",
        "lat": 26.1445,
        "lng": 91.7362,
        "datetime": "2026-08-28T03:15:00+05:30",
        "description": "The Brahmaputra crossed the danger mark, breaching an embankment and submerging farmland across several villages.",
        "source": "Government",
        "source_name": "Assam State Disaster Management Authority",
        "trust_score": 95,
        "status": "high-risk",
        "media_url": "/media/flood.png",
        "ml_classification": "Flood — Riverine",
        "ml_confidence": 0.96,
        "affected_population": 132000,
    },
    {
        "id": "evt-1008",
        "type": "Heavy Rain",
        "title": "Monsoon surge over Western Ghats",
        "state": "Karnataka",
        "city": "Madikeri",
        "lat": 12.4244,
        "lng": 75.7382,
        "datetime": "2026-08-27T20:00:00+05:30",
        "description": "Orange alert as heavy to very heavy rainfall lashes the Kodagu region. Reservoir inflow rising sharply.",
        "source": "News Website",
        "source_name": "National Weather Wire",
        "trust_score": 79,
        "status": "verified",
        "media_url": "/media/heavy-rain.png",
        "ml_classification": "Heavy Rainfall — High",
        "ml_confidence": 0.88,
        "affected_population": 18000,
    },
    {
        "id": "evt-1009",
        "type": "Storm",
        "title": "Dust storm reduces visibility",
        "state": "Delhi",
        "city": "New Delhi",
        "lat": 28.6139,
        "lng": 77.209,
        "datetime": "2026-08-27T18:40:00+05:30",
        "description": "A sudden dust storm brought visibility down to under 500m. Flights briefly delayed at the airport.",
        "source": "Social Media",
        "source_name": "Aggregated social signals",
        "trust_score": 61,
        "status": "pending",
        "media_url": "/media/storm.png",
        "ml_classification": "Dust Storm — Moderate",
        "ml_confidence": 0.75,
        "affected_population": 40000,
    },
    {
        "id": "evt-1010",
        "type": "Cyclone",
        "title": "Coastal wind warning issued",
        "state": "Andhra Pradesh",
        "city": "Visakhapatnam",
        "lat": 17.6868,
        "lng": 83.2185,
        "datetime": "2026-08-28T02:00:00+05:30",
        "description": "Fishermen advised not to venture into the sea as a low pressure system strengthens off the coast.",
        "source": "Government",
        "source_name": "India Meteorological Department",
        "trust_score": 90,
        "status": "verified",
        "media_url": "/media/cyclone.png",
        "ml_classification": "Cyclone — Developing",
        "ml_confidence": 0.85,
        "affected_population": 56000,
    },
]

for data in events:
    existing = db.query(WeatherEvent).filter(
        WeatherEvent.id == data["id"]
    ).first()

    if not existing:
        db.add(WeatherEvent(**data))

db.commit()
db.close()

print(f"Inserted {len(events)} weather events.")